
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  nginx:
    image: nginx:alpine3.22
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tivon1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgresql
    ports:
      - "5433:5432"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d datos"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    depends_on:
      - postgres

  webapp:
    image: ghcr.io/agusvolpe/academianovit:latest
    ports:
      - "8080:8080"
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - app-network
    depends_on:
      - postgres
      - seq
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=datos;Username=admin;Password=tivon1234
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=tivon1234
    ports:
      - "5353:80"
      - "5342:5341"
    volumes:
      - seq-data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

volumes:
    postgres:
    pgadmin:
    seq-data:
    portainer-data:
